In [12]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import metrics,preprocessing

In [2]:
df = pd.read_csv(r"C:\Users\nayan\Desktop\datasets\diabetes.csv")

In [76]:
df.head()



Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
114            7      160             54             32      175  30.5   
168            4      110             66              0        0  31.9   
230            4      142             86              0        0  44.0   
379            0       93            100             39       72  43.4   
439            6      107             88              0        0  36.8   

     DiabetesPedigreeFunction  Age  Outcome  
114                     0.588   39        1  
168                     0.471   29        0  
230                     0.645   22        1  
379                     1.021   35        0  
439                     0.727   31        0

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df=sklearn.utils.shuffle(df)

In [42]:
X = df.drop("Outcome", axis=1).values
y = df["Outcome"].values

In [79]:
logistic_model.predict(X[0])

ValueError: Expected 2D array, got 1D array instead:
array=[  7.    160.     54.     32.    175.     30.5     0.588  39.   ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [46]:
y

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

In [48]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
MultinomialNB_model = MultinomialNB()

In [50]:
MultinomialNB_model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [51]:
pred = MultinomialNB_model.predict(X_test)

In [52]:
acc = metrics.accuracy_score(y_test, pred)

In [53]:
print("accuracy", acc*100)

accuracy 59.09090909090909


In [54]:
from sklearn.naive_bayes import BernoulliNB


In [55]:
BernoulliNB_model = BernoulliNB()

In [56]:
BernoulliNB_model.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [57]:
pred = BernoulliNB_model.predict(X_test)

In [58]:
acc = metrics.accuracy_score(y_test, pred)

In [59]:
print("accuracy", acc*100)

accuracy 57.14285714285714


In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
logistic_model=LogisticRegression(random_state=0, solver='lbfgs' ,multi_class='multinomial').fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [62]:
pred=logistic_model.predict(X_test)

In [64]:
acc=metrics.accuracy_score(y_test,pred)

In [65]:
print("accuracy", acc*100)

accuracy 72.07792207792207


In [90]:
Y = [[4, 142, 86, 0, 0, 44.0, 0.645, 22]]
a = np.asarray(Y) 

In [66]:
from sklearn.linear_model import SGDClassifier

In [91]:
a

array([[  4.   , 142.   ,  86.   ,   0.   ,   0.   ,  44.   ,   0.645,
         22.   ]])

In [86]:
X_test[0]

array([ 10.   , 133.   ,  68.   ,   0.   ,   0.   ,  27.   ,   0.245,
        36.   ])

In [92]:
logistic_model.predict(a)

array([1], dtype=int64)

In [89]:
X_test


array([[ 10.   , 133.   ,  68.   , ...,  27.   ,   0.245,  36.   ],
       [  3.   , 132.   ,  80.   , ...,  34.4  ,   0.402,  44.   ],
       [  9.   , 145.   ,  80.   , ...,  37.9  ,   0.637,  40.   ],
       ...,
       [  1.   , 189.   ,  60.   , ...,  30.1  ,   0.398,  59.   ],
       [  0.   , 107.   ,  76.   , ...,  45.3  ,   0.686,  24.   ],
       [  4.   , 141.   ,  74.   , ...,  27.6  ,   0.244,  40.   ]])

In [67]:
sgd_model = SGDClassifier(max_iter=1000 ,random_state=125)

In [68]:
sgd_model.fit(X_train ,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=125, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [69]:
pred=sgd_model.predict(X_test)

In [70]:
acc=metrics.accuracy_score(y_test,pred)

In [71]:
print('acuuracy =',acc*100)

acuuracy = 46.103896103896105


In [72]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model=RandomForestClassifier(n_estimators=1, max_depth=3, random_state=0)

random_forest_model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [73]:
pred=random_forest_model.predict(X_test)

acc=metrics.accuracy_score(y_test,pred)

print('acuuracy =',acc*100)

acuuracy = 64.93506493506493
